spring:
    datasource:
        name: database
        url: jdbc:postgresql://localhost:5432/cities
        username: postgres
        password: 12345
    jpa:
        properties:
            #generate-ddl: true
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                show-sql: true

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
